// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVX5xS4niK2gFJRgAE9oBuOJBNR2ZdeI',
    appId: '1:887354715842:web:84279277e19bd45b19955b',
    messagingSenderId: '887354715842',
    projectId: 'medicine-reminders',
    authDomain: 'medicine-reminders.firebaseapp.com',
    storageBucket: 'medicine-reminders.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSpMzue846m64a0RtGqFPY4BP3zFXsr4E',
    appId: '1:887354715842:android:0aed7dca9d24465919955b',
    messagingSenderId: '887354715842',
    projectId: 'medicine-reminders',
    storageBucket: 'medicine-reminders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNzYz8ZLhK8GAraBVPGNm1yVhbWZysmW4',
    appId: '1:887354715842:ios:350fc0b6808bcc3119955b',
    messagingSenderId: '887354715842',
    projectId: 'medicine-reminders',
    storageBucket: 'medicine-reminders.appspot.com',
    iosClientId: '887354715842-6obd057k0fmpcd02hvkiech7cgoa2uvj.apps.googleusercontent.com',
    iosBundleId: 'com.bryangerlach.medicinereminderflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNzYz8ZLhK8GAraBVPGNm1yVhbWZysmW4',
    appId: '1:887354715842:ios:350fc0b6808bcc3119955b',
    messagingSenderId: '887354715842',
    projectId: 'medicine-reminders',
    storageBucket: 'medicine-reminders.appspot.com',
    iosClientId: '887354715842-6obd057k0fmpcd02hvkiech7cgoa2uvj.apps.googleusercontent.com',
    iosBundleId: 'com.bryangerlach.medicinereminderflutter',
  );
}
