name: Build Android APK

on:
  push:
    branches: [ master ] # Trigger on pushes to the master branch (adjust as needed)
  workflow_dispatch: # Enable manual triggering of the workflow

jobs:
  build:
    name: Build and Sign APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Or your preferred Java version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Specify your desired Flutter version (e.g., 'stable', '3.10.x')
          channel: 'stable' # Or 'beta', 'dev'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Load environment variables
        run: |
          echo "${{ secrets.DOT_ENV_CONTENT }}" > .env

      - name: Build Android APK
        run: flutter build apk --split-per-abi # Or flutter build apk

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        continue-on-error: true
        id: sign-medicinereminder
        with:
          releaseDirectory: build/app/outputs/apk/release/
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ 'build/app/outputs/apk/release/app-release-signed.apk' || 'build/app/outputs/apk/release/app-release.apk' }}